//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pariwisata_Apps
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PariwisataEntities : DbContext
    {
        public PariwisataEntities()
            : base("name=PariwisataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Place> Places { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
        public virtual DbSet<TourMenu> TourMenus { get; set; }
        public virtual DbSet<Transportation> Transportations { get; set; }
        public virtual DbSet<TransType> TransTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
