//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pariwisata_Apps
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TourMenu()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int MenuID { get; set; }
        public int PlaceID { get; set; }
        public string Name { get; set; }
        public byte[] Image { get; set; }
        public string Benefit { get; set; }
        public int QuotaPerDay { get; set; }
        public int Price { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual Place Place { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
